/*
 * RMA_RestAPI_Design_1
 * Customer Requirements from Excel Document RMA_RestAPI_Design 1.xlsx
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Attachment;
import io.swagger.client.model.Error;
import java.io.File;
import io.swagger.client.model.InlineResponse201;
import io.swagger.client.model.Note;
import io.swagger.client.model.NoteCreate;
import org.threeten.bp.OffsetDateTime;
import io.swagger.client.model.TacCase;
import io.swagger.client.model.TacCaseCreate;
import io.swagger.client.model.TacCaseStatus;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TacCaseApi
 */
@Ignore
public class TacCaseApiTest {

    private final TacCaseApi api = new TacCaseApi();

    /**
     * Creates a TAC Case
     *
     * This operation creates a tacCase entity.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTacCaseTest() throws Exception {
        TacCaseCreate body = null;
        TacCase response = api.createTacCase(body);

        // TODO: test validations
    }
    /**
     * Creates a note assocated with a TAC Case
     *
     * This operation creates adds a Case Note to a TAC Case
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTacCaseNoteTest() throws Exception {
        NoteCreate body = null;
        String caseNumber = null;
        Note response = api.createTacCaseNote(body, caseNumber);

        // TODO: test validations
    }
    /**
     * Get a list of attachments for a specific TAC case
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTacCaseAttachmentsTest() throws Exception {
        String caseNumber = null;
        Integer offset = null;
        Integer limit = null;
        List<Attachment> response = api.getTacCaseAttachments(caseNumber, offset, limit);

        // TODO: test validations
    }
    /**
     * Get notes for a specific TAC Case
     *
     * Retrieve a list of notes attached to a specific item by its TAC Case Number.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTacCaseNotesTest() throws Exception {
        String caseNumber = null;
        Integer offset = null;
        Integer limit = null;
        OffsetDateTime createdFrom = null;
        OffsetDateTime createdTo = null;
        OffsetDateTime createdSince = null;
        List<Note> response = api.getTacCaseNotes(caseNumber, offset, limit, createdFrom, createdTo, createdSince);

        // TODO: test validations
    }
    /**
     * List or find TAC Cases
     *
     * This operation list or find TACCase entities
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listTacCasesTest() throws Exception {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        OffsetDateTime createdFrom = null;
        OffsetDateTime createdTo = null;
        OffsetDateTime createdSince = null;
        TacCaseStatus caseStatus = null;
        Boolean includeNotes = null;
        List<TacCase> response = api.listTacCases(fields, offset, limit, createdFrom, createdTo, createdSince, caseStatus, includeNotes);

        // TODO: test validations
    }
    /**
     * Retrieves a TAC Case by ID
     *
     * This operation retrieves a tacCase entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void retrieveTacCaseTest() throws Exception {
        String caseNumber = null;
        String fields = null;
        Boolean includeNotes = null;
        TacCase response = api.retrieveTacCase(caseNumber, fields, includeNotes);

        // TODO: test validations
    }
    /**
     * Retrieves a TAC Case Attachment by ID
     *
     * This operation retrieves an TAC Case Attachment
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void retrieveTacCaseAttachmentTest() throws Exception {
        String caseNumber = null;
        String id = null;
        String fields = null;
        List<Attachment> response = api.retrieveTacCaseAttachment(caseNumber, id, fields);

        // TODO: test validations
    }
    /**
     * Retrieves a TAC Case Note by ID
     *
     * This operation retrieves a CaseNote entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void retrieveTacCaseNoteTest() throws Exception {
        String caseNumber = null;
        String id = null;
        Note response = api.retrieveTacCaseNote(caseNumber, id);

        // TODO: test validations
    }
    /**
     * Updates a TAC Case by ID
     *
     * This operation updates a tacCase entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTacCaseTest() throws Exception {
        TacCase body = null;
        String caseNumber = null;
        api.updateTacCase(body, caseNumber);

        // TODO: test validations
    }
    /**
     * Updates a TAC Case Note by ID
     *
     * This operation updates a TAC Case Note. Attribute selection is enabled for all first level attributes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTacCaseNoteTest() throws Exception {
        Note body = null;
        String caseNumber = null;
        String id = null;
        api.updateTacCaseNote(body, caseNumber, id);

        // TODO: test validations
    }
    /**
     * Upload an attachment to a specific TAC case
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadTacCaseAttachmentTest() throws Exception {
        File file = null;
        String description = null;
        String caseNumber = null;
        InlineResponse201 response = api.uploadTacCaseAttachment(file, description, caseNumber);

        // TODO: test validations
    }
}
