/*
 * RMA_RestAPI_Design_1
 * Customer Requirements from Excel Document RMA_RestAPI_Design 1.xlsx
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * CommonCreateCaseProperties
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-29T19:29:38.424806759Z[GMT]")

public class CommonCreateCaseProperties {
  @SerializedName("requestDate")
  private OffsetDateTime requestDate = null;

  @SerializedName("requestorOrganization")
  private String requestorOrganization = null;

  @SerializedName("requestorFirstName")
  private String requestorFirstName = null;

  @SerializedName("requestorLastName")
  private String requestorLastName = null;

  @SerializedName("requestorEmail")
  private Object requestorEmail = null;

  @SerializedName("requestorPhone")
  private Object requestorPhone = null;

  @SerializedName("installationCountry")
  private String installationCountry = null;

  /**
   * Gets or Sets networkStatus
   */
  @JsonAdapter(NetworkStatusEnum.Adapter.class)
  public enum NetworkStatusEnum {
    @SerializedName("Production")
    PRODUCTION("Production"),
    @SerializedName("Test")
    TEST("Test"),
    @SerializedName("Development")
    DEVELOPMENT("Development");

    private String value;

    NetworkStatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static NetworkStatusEnum fromValue(String input) {
      for (NetworkStatusEnum b : NetworkStatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<NetworkStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NetworkStatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public NetworkStatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return NetworkStatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("networkStatus")
  private NetworkStatusEnum networkStatus = null;

  @SerializedName("businessImpact")
  private String businessImpact = null;

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("problemDescription")
  private String problemDescription = null;

  @SerializedName("productName")
  private String productName = null;

  @SerializedName("productSerialNumber")
  private String productSerialNumber = null;

  @SerializedName("productFirmwareVersion")
  private String productFirmwareVersion = null;

  @SerializedName("productSoftwareVersion")
  private String productSoftwareVersion = null;

  @SerializedName("outageStartTime")
  private OffsetDateTime outageStartTime = null;

  @SerializedName("outageRecoveryTime")
  private OffsetDateTime outageRecoveryTime = null;

  @SerializedName("customerTrackingNumber")
  private String customerTrackingNumber = null;

  public CommonCreateCaseProperties requestDate(OffsetDateTime requestDate) {
    this.requestDate = requestDate;
    return this;
  }

   /**
   * The date on which the TAC Case create was requested
   * @return requestDate
  **/
  @Schema(description = "The date on which the TAC Case create was requested")
  public OffsetDateTime getRequestDate() {
    return requestDate;
  }

  public void setRequestDate(OffsetDateTime requestDate) {
    this.requestDate = requestDate;
  }

  public CommonCreateCaseProperties requestorOrganization(String requestorOrganization) {
    this.requestorOrganization = requestorOrganization;
    return this;
  }

   /**
   * The Organization that is requesting the TAC Case
   * @return requestorOrganization
  **/
  @Schema(example = "[\"MSFT\"]", description = "The Organization that is requesting the TAC Case")
  public String getRequestorOrganization() {
    return requestorOrganization;
  }

  public void setRequestorOrganization(String requestorOrganization) {
    this.requestorOrganization = requestorOrganization;
  }

  public CommonCreateCaseProperties requestorFirstName(String requestorFirstName) {
    this.requestorFirstName = requestorFirstName;
    return this;
  }

   /**
   * Get requestorFirstName
   * @return requestorFirstName
  **/
  @Schema(description = "")
  public String getRequestorFirstName() {
    return requestorFirstName;
  }

  public void setRequestorFirstName(String requestorFirstName) {
    this.requestorFirstName = requestorFirstName;
  }

  public CommonCreateCaseProperties requestorLastName(String requestorLastName) {
    this.requestorLastName = requestorLastName;
    return this;
  }

   /**
   * Get requestorLastName
   * @return requestorLastName
  **/
  @Schema(description = "")
  public String getRequestorLastName() {
    return requestorLastName;
  }

  public void setRequestorLastName(String requestorLastName) {
    this.requestorLastName = requestorLastName;
  }

  public CommonCreateCaseProperties requestorEmail(Object requestorEmail) {
    this.requestorEmail = requestorEmail;
    return this;
  }

   /**
   * Get requestorEmail
   * @return requestorEmail
  **/
  @Schema(description = "")
  public Object getRequestorEmail() {
    return requestorEmail;
  }

  public void setRequestorEmail(Object requestorEmail) {
    this.requestorEmail = requestorEmail;
  }

  public CommonCreateCaseProperties requestorPhone(Object requestorPhone) {
    this.requestorPhone = requestorPhone;
    return this;
  }

   /**
   * Get requestorPhone
   * @return requestorPhone
  **/
  @Schema(description = "")
  public Object getRequestorPhone() {
    return requestorPhone;
  }

  public void setRequestorPhone(Object requestorPhone) {
    this.requestorPhone = requestorPhone;
  }

  public CommonCreateCaseProperties installationCountry(String installationCountry) {
    this.installationCountry = installationCountry;
    return this;
  }

   /**
   * Get installationCountry
   * @return installationCountry
  **/
  @Schema(description = "")
  public String getInstallationCountry() {
    return installationCountry;
  }

  public void setInstallationCountry(String installationCountry) {
    this.installationCountry = installationCountry;
  }

  public CommonCreateCaseProperties networkStatus(NetworkStatusEnum networkStatus) {
    this.networkStatus = networkStatus;
    return this;
  }

   /**
   * Get networkStatus
   * @return networkStatus
  **/
  @Schema(description = "")
  public NetworkStatusEnum getNetworkStatus() {
    return networkStatus;
  }

  public void setNetworkStatus(NetworkStatusEnum networkStatus) {
    this.networkStatus = networkStatus;
  }

  public CommonCreateCaseProperties businessImpact(String businessImpact) {
    this.businessImpact = businessImpact;
    return this;
  }

   /**
   * The impact to the customer&#x27;s business associated with this Case
   * @return businessImpact
  **/
  @Schema(example = "[\"Critical level business impacting issue\",\"Major level business impacting issue\",\"Minor level business impacting issue\",\"Warning level business impacting issue\"]", description = "The impact to the customer's business associated with this Case")
  public String getBusinessImpact() {
    return businessImpact;
  }

  public void setBusinessImpact(String businessImpact) {
    this.businessImpact = businessImpact;
  }

  public CommonCreateCaseProperties subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Subject of TAC Case
   * @return subject
  **/
  @Schema(description = "Subject of TAC Case")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public CommonCreateCaseProperties problemDescription(String problemDescription) {
    this.problemDescription = problemDescription;
    return this;
  }

   /**
   * Description of the issue in this case
   * @return problemDescription
  **/
  @Schema(description = "Description of the issue in this case")
  public String getProblemDescription() {
    return problemDescription;
  }

  public void setProblemDescription(String problemDescription) {
    this.problemDescription = problemDescription;
  }

  public CommonCreateCaseProperties productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * The name of the product associated with this TAC Case
   * @return productName
  **/
  @Schema(description = "The name of the product associated with this TAC Case")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public CommonCreateCaseProperties productSerialNumber(String productSerialNumber) {
    this.productSerialNumber = productSerialNumber;
    return this;
  }

   /**
   * The serial number of the product associated with this TAC Case
   * @return productSerialNumber
  **/
  @Schema(description = "The serial number of the product associated with this TAC Case")
  public String getProductSerialNumber() {
    return productSerialNumber;
  }

  public void setProductSerialNumber(String productSerialNumber) {
    this.productSerialNumber = productSerialNumber;
  }

  public CommonCreateCaseProperties productFirmwareVersion(String productFirmwareVersion) {
    this.productFirmwareVersion = productFirmwareVersion;
    return this;
  }

   /**
   * The version number of the product associated with this TAC Case
   * @return productFirmwareVersion
  **/
  @Schema(description = "The version number of the product associated with this TAC Case")
  public String getProductFirmwareVersion() {
    return productFirmwareVersion;
  }

  public void setProductFirmwareVersion(String productFirmwareVersion) {
    this.productFirmwareVersion = productFirmwareVersion;
  }

  public CommonCreateCaseProperties productSoftwareVersion(String productSoftwareVersion) {
    this.productSoftwareVersion = productSoftwareVersion;
    return this;
  }

   /**
   * The version number of the product associated with this TAC Case
   * @return productSoftwareVersion
  **/
  @Schema(description = "The version number of the product associated with this TAC Case")
  public String getProductSoftwareVersion() {
    return productSoftwareVersion;
  }

  public void setProductSoftwareVersion(String productSoftwareVersion) {
    this.productSoftwareVersion = productSoftwareVersion;
  }

  public CommonCreateCaseProperties outageStartTime(OffsetDateTime outageStartTime) {
    this.outageStartTime = outageStartTime;
    return this;
  }

   /**
   * The date and time that the outage associated with this case was detected
   * @return outageStartTime
  **/
  @Schema(description = "The date and time that the outage associated with this case was detected")
  public OffsetDateTime getOutageStartTime() {
    return outageStartTime;
  }

  public void setOutageStartTime(OffsetDateTime outageStartTime) {
    this.outageStartTime = outageStartTime;
  }

  public CommonCreateCaseProperties outageRecoveryTime(OffsetDateTime outageRecoveryTime) {
    this.outageRecoveryTime = outageRecoveryTime;
    return this;
  }

   /**
   * The date and time that the outage associated with this case was recovered
   * @return outageRecoveryTime
  **/
  @Schema(description = "The date and time that the outage associated with this case was recovered")
  public OffsetDateTime getOutageRecoveryTime() {
    return outageRecoveryTime;
  }

  public void setOutageRecoveryTime(OffsetDateTime outageRecoveryTime) {
    this.outageRecoveryTime = outageRecoveryTime;
  }

  public CommonCreateCaseProperties customerTrackingNumber(String customerTrackingNumber) {
    this.customerTrackingNumber = customerTrackingNumber;
    return this;
  }

   /**
   * A Reference to the customer&#x27;s issue associated with this Case
   * @return customerTrackingNumber
  **/
  @Schema(description = "A Reference to the customer's issue associated with this Case")
  public String getCustomerTrackingNumber() {
    return customerTrackingNumber;
  }

  public void setCustomerTrackingNumber(String customerTrackingNumber) {
    this.customerTrackingNumber = customerTrackingNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonCreateCaseProperties commonCreateCaseProperties = (CommonCreateCaseProperties) o;
    return Objects.equals(this.requestDate, commonCreateCaseProperties.requestDate) &&
        Objects.equals(this.requestorOrganization, commonCreateCaseProperties.requestorOrganization) &&
        Objects.equals(this.requestorFirstName, commonCreateCaseProperties.requestorFirstName) &&
        Objects.equals(this.requestorLastName, commonCreateCaseProperties.requestorLastName) &&
        Objects.equals(this.requestorEmail, commonCreateCaseProperties.requestorEmail) &&
        Objects.equals(this.requestorPhone, commonCreateCaseProperties.requestorPhone) &&
        Objects.equals(this.installationCountry, commonCreateCaseProperties.installationCountry) &&
        Objects.equals(this.networkStatus, commonCreateCaseProperties.networkStatus) &&
        Objects.equals(this.businessImpact, commonCreateCaseProperties.businessImpact) &&
        Objects.equals(this.subject, commonCreateCaseProperties.subject) &&
        Objects.equals(this.problemDescription, commonCreateCaseProperties.problemDescription) &&
        Objects.equals(this.productName, commonCreateCaseProperties.productName) &&
        Objects.equals(this.productSerialNumber, commonCreateCaseProperties.productSerialNumber) &&
        Objects.equals(this.productFirmwareVersion, commonCreateCaseProperties.productFirmwareVersion) &&
        Objects.equals(this.productSoftwareVersion, commonCreateCaseProperties.productSoftwareVersion) &&
        Objects.equals(this.outageStartTime, commonCreateCaseProperties.outageStartTime) &&
        Objects.equals(this.outageRecoveryTime, commonCreateCaseProperties.outageRecoveryTime) &&
        Objects.equals(this.customerTrackingNumber, commonCreateCaseProperties.customerTrackingNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestDate, requestorOrganization, requestorFirstName, requestorLastName, requestorEmail, requestorPhone, installationCountry, networkStatus, businessImpact, subject, problemDescription, productName, productSerialNumber, productFirmwareVersion, productSoftwareVersion, outageStartTime, outageRecoveryTime, customerTrackingNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonCreateCaseProperties {\n");
    
    sb.append("    requestDate: ").append(toIndentedString(requestDate)).append("\n");
    sb.append("    requestorOrganization: ").append(toIndentedString(requestorOrganization)).append("\n");
    sb.append("    requestorFirstName: ").append(toIndentedString(requestorFirstName)).append("\n");
    sb.append("    requestorLastName: ").append(toIndentedString(requestorLastName)).append("\n");
    sb.append("    requestorEmail: ").append(toIndentedString(requestorEmail)).append("\n");
    sb.append("    requestorPhone: ").append(toIndentedString(requestorPhone)).append("\n");
    sb.append("    installationCountry: ").append(toIndentedString(installationCountry)).append("\n");
    sb.append("    networkStatus: ").append(toIndentedString(networkStatus)).append("\n");
    sb.append("    businessImpact: ").append(toIndentedString(businessImpact)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    problemDescription: ").append(toIndentedString(problemDescription)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    productSerialNumber: ").append(toIndentedString(productSerialNumber)).append("\n");
    sb.append("    productFirmwareVersion: ").append(toIndentedString(productFirmwareVersion)).append("\n");
    sb.append("    productSoftwareVersion: ").append(toIndentedString(productSoftwareVersion)).append("\n");
    sb.append("    outageStartTime: ").append(toIndentedString(outageStartTime)).append("\n");
    sb.append("    outageRecoveryTime: ").append(toIndentedString(outageRecoveryTime)).append("\n");
    sb.append("    customerTrackingNumber: ").append(toIndentedString(customerTrackingNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
