/*
 * RMA_RestAPI_Design_1
 * Customer Requirements from Excel Document RMA_RestAPI_Design 1.xlsx
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * CommonNoteProperties
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-29T19:29:38.424806759Z[GMT]")

public class CommonNoteProperties {
  @SerializedName("author")
  private String author = null;

  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("text")
  private String text = null;

  public CommonNoteProperties author(String author) {
    this.author = author;
    return this;
  }

   /**
   * Author of the note
   * @return author
  **/
  @Schema(description = "Author of the note")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public CommonNoteProperties date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Date of the note
   * @return date
  **/
  @Schema(description = "Date of the note")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public CommonNoteProperties text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Text of the note
   * @return text
  **/
  @Schema(description = "Text of the note")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonNoteProperties commonNoteProperties = (CommonNoteProperties) o;
    return Objects.equals(this.author, commonNoteProperties.author) &&
        Objects.equals(this.date, commonNoteProperties.date) &&
        Objects.equals(this.text, commonNoteProperties.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, date, text);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonNoteProperties {\n");
    
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
