/*
 * RMA_RestAPI_Design_1
 * Customer Requirements from Excel Document RMA_RestAPI_Design 1.xlsx
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CommonCreateCaseProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * A TAC Case is a record of an issue that is created, tracked, and managed by the TAC Case management system Skipped properties: id,href
 */
@Schema(description = "A TAC Case is a record of an issue that is created, tracked, and managed by the TAC Case management system Skipped properties: id,href")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-29T19:29:38.424806759Z[GMT]")

public class RmaCaseCreate extends CommonCreateCaseProperties {
  @SerializedName("relatedTacCaseId")
  private String relatedTacCaseId = null;

  @SerializedName("faultySerialNumber")
  private String faultySerialNumber = null;

  @SerializedName("RequesterShippingFirstName")
  private String requesterShippingFirstName = null;

  @SerializedName("RequesterShippingLastName")
  private String requesterShippingLastName = null;

  @SerializedName("RequesterShippingEmail")
  private String requesterShippingEmail = null;

  @SerializedName("RequesterShippingPhone")
  private String requesterShippingPhone = null;

  @SerializedName("RequesterShippingStreet")
  private String requesterShippingStreet = null;

  @SerializedName("RequesterShippingCity")
  private String requesterShippingCity = null;

  @SerializedName("RequesterShippingStateProvince")
  private String requesterShippingStateProvince = null;

  @SerializedName("RequesterShippingCountry")
  private String requesterShippingCountry = null;

  @SerializedName("RequesterShippingPostalCode")
  private String requesterShippingPostalCode = null;

  @SerializedName("ShippingInboundId")
  private String shippingInboundId = null;

  @SerializedName("ShippingOutboundId")
  private String shippingOutboundId = null;

  public RmaCaseCreate relatedTacCaseId(String relatedTacCaseId) {
    this.relatedTacCaseId = relatedTacCaseId;
    return this;
  }

   /**
   * This assumes that an RMA case is a child case to an existing TAC Case
   * @return relatedTacCaseId
  **/
  @Schema(description = "This assumes that an RMA case is a child case to an existing TAC Case")
  public String getRelatedTacCaseId() {
    return relatedTacCaseId;
  }

  public void setRelatedTacCaseId(String relatedTacCaseId) {
    this.relatedTacCaseId = relatedTacCaseId;
  }

  public RmaCaseCreate faultySerialNumber(String faultySerialNumber) {
    this.faultySerialNumber = faultySerialNumber;
    return this;
  }

   /**
   * This is the serial number of the faulty device requiring the RMA
   * @return faultySerialNumber
  **/
  @Schema(description = "This is the serial number of the faulty device requiring the RMA")
  public String getFaultySerialNumber() {
    return faultySerialNumber;
  }

  public void setFaultySerialNumber(String faultySerialNumber) {
    this.faultySerialNumber = faultySerialNumber;
  }

  public RmaCaseCreate requesterShippingFirstName(String requesterShippingFirstName) {
    this.requesterShippingFirstName = requesterShippingFirstName;
    return this;
  }

   /**
   * Get requesterShippingFirstName
   * @return requesterShippingFirstName
  **/
  @Schema(description = "")
  public String getRequesterShippingFirstName() {
    return requesterShippingFirstName;
  }

  public void setRequesterShippingFirstName(String requesterShippingFirstName) {
    this.requesterShippingFirstName = requesterShippingFirstName;
  }

  public RmaCaseCreate requesterShippingLastName(String requesterShippingLastName) {
    this.requesterShippingLastName = requesterShippingLastName;
    return this;
  }

   /**
   * Get requesterShippingLastName
   * @return requesterShippingLastName
  **/
  @Schema(description = "")
  public String getRequesterShippingLastName() {
    return requesterShippingLastName;
  }

  public void setRequesterShippingLastName(String requesterShippingLastName) {
    this.requesterShippingLastName = requesterShippingLastName;
  }

  public RmaCaseCreate requesterShippingEmail(String requesterShippingEmail) {
    this.requesterShippingEmail = requesterShippingEmail;
    return this;
  }

   /**
   * Get requesterShippingEmail
   * @return requesterShippingEmail
  **/
  @Schema(description = "")
  public String getRequesterShippingEmail() {
    return requesterShippingEmail;
  }

  public void setRequesterShippingEmail(String requesterShippingEmail) {
    this.requesterShippingEmail = requesterShippingEmail;
  }

  public RmaCaseCreate requesterShippingPhone(String requesterShippingPhone) {
    this.requesterShippingPhone = requesterShippingPhone;
    return this;
  }

   /**
   * Get requesterShippingPhone
   * @return requesterShippingPhone
  **/
  @Schema(description = "")
  public String getRequesterShippingPhone() {
    return requesterShippingPhone;
  }

  public void setRequesterShippingPhone(String requesterShippingPhone) {
    this.requesterShippingPhone = requesterShippingPhone;
  }

  public RmaCaseCreate requesterShippingStreet(String requesterShippingStreet) {
    this.requesterShippingStreet = requesterShippingStreet;
    return this;
  }

   /**
   * Get requesterShippingStreet
   * @return requesterShippingStreet
  **/
  @Schema(description = "")
  public String getRequesterShippingStreet() {
    return requesterShippingStreet;
  }

  public void setRequesterShippingStreet(String requesterShippingStreet) {
    this.requesterShippingStreet = requesterShippingStreet;
  }

  public RmaCaseCreate requesterShippingCity(String requesterShippingCity) {
    this.requesterShippingCity = requesterShippingCity;
    return this;
  }

   /**
   * Get requesterShippingCity
   * @return requesterShippingCity
  **/
  @Schema(description = "")
  public String getRequesterShippingCity() {
    return requesterShippingCity;
  }

  public void setRequesterShippingCity(String requesterShippingCity) {
    this.requesterShippingCity = requesterShippingCity;
  }

  public RmaCaseCreate requesterShippingStateProvince(String requesterShippingStateProvince) {
    this.requesterShippingStateProvince = requesterShippingStateProvince;
    return this;
  }

   /**
   * Get requesterShippingStateProvince
   * @return requesterShippingStateProvince
  **/
  @Schema(description = "")
  public String getRequesterShippingStateProvince() {
    return requesterShippingStateProvince;
  }

  public void setRequesterShippingStateProvince(String requesterShippingStateProvince) {
    this.requesterShippingStateProvince = requesterShippingStateProvince;
  }

  public RmaCaseCreate requesterShippingCountry(String requesterShippingCountry) {
    this.requesterShippingCountry = requesterShippingCountry;
    return this;
  }

   /**
   * Get requesterShippingCountry
   * @return requesterShippingCountry
  **/
  @Schema(description = "")
  public String getRequesterShippingCountry() {
    return requesterShippingCountry;
  }

  public void setRequesterShippingCountry(String requesterShippingCountry) {
    this.requesterShippingCountry = requesterShippingCountry;
  }

  public RmaCaseCreate requesterShippingPostalCode(String requesterShippingPostalCode) {
    this.requesterShippingPostalCode = requesterShippingPostalCode;
    return this;
  }

   /**
   * Get requesterShippingPostalCode
   * @return requesterShippingPostalCode
  **/
  @Schema(description = "")
  public String getRequesterShippingPostalCode() {
    return requesterShippingPostalCode;
  }

  public void setRequesterShippingPostalCode(String requesterShippingPostalCode) {
    this.requesterShippingPostalCode = requesterShippingPostalCode;
  }

  public RmaCaseCreate shippingInboundId(String shippingInboundId) {
    this.shippingInboundId = shippingInboundId;
    return this;
  }

   /**
   * Get shippingInboundId
   * @return shippingInboundId
  **/
  @Schema(description = "")
  public String getShippingInboundId() {
    return shippingInboundId;
  }

  public void setShippingInboundId(String shippingInboundId) {
    this.shippingInboundId = shippingInboundId;
  }

  public RmaCaseCreate shippingOutboundId(String shippingOutboundId) {
    this.shippingOutboundId = shippingOutboundId;
    return this;
  }

   /**
   * Get shippingOutboundId
   * @return shippingOutboundId
  **/
  @Schema(description = "")
  public String getShippingOutboundId() {
    return shippingOutboundId;
  }

  public void setShippingOutboundId(String shippingOutboundId) {
    this.shippingOutboundId = shippingOutboundId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RmaCaseCreate rmaCaseCreate = (RmaCaseCreate) o;
    return Objects.equals(this.relatedTacCaseId, rmaCaseCreate.relatedTacCaseId) &&
        Objects.equals(this.faultySerialNumber, rmaCaseCreate.faultySerialNumber) &&
        Objects.equals(this.requesterShippingFirstName, rmaCaseCreate.requesterShippingFirstName) &&
        Objects.equals(this.requesterShippingLastName, rmaCaseCreate.requesterShippingLastName) &&
        Objects.equals(this.requesterShippingEmail, rmaCaseCreate.requesterShippingEmail) &&
        Objects.equals(this.requesterShippingPhone, rmaCaseCreate.requesterShippingPhone) &&
        Objects.equals(this.requesterShippingStreet, rmaCaseCreate.requesterShippingStreet) &&
        Objects.equals(this.requesterShippingCity, rmaCaseCreate.requesterShippingCity) &&
        Objects.equals(this.requesterShippingStateProvince, rmaCaseCreate.requesterShippingStateProvince) &&
        Objects.equals(this.requesterShippingCountry, rmaCaseCreate.requesterShippingCountry) &&
        Objects.equals(this.requesterShippingPostalCode, rmaCaseCreate.requesterShippingPostalCode) &&
        Objects.equals(this.shippingInboundId, rmaCaseCreate.shippingInboundId) &&
        Objects.equals(this.shippingOutboundId, rmaCaseCreate.shippingOutboundId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relatedTacCaseId, faultySerialNumber, requesterShippingFirstName, requesterShippingLastName, requesterShippingEmail, requesterShippingPhone, requesterShippingStreet, requesterShippingCity, requesterShippingStateProvince, requesterShippingCountry, requesterShippingPostalCode, shippingInboundId, shippingOutboundId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RmaCaseCreate {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    relatedTacCaseId: ").append(toIndentedString(relatedTacCaseId)).append("\n");
    sb.append("    faultySerialNumber: ").append(toIndentedString(faultySerialNumber)).append("\n");
    sb.append("    requesterShippingFirstName: ").append(toIndentedString(requesterShippingFirstName)).append("\n");
    sb.append("    requesterShippingLastName: ").append(toIndentedString(requesterShippingLastName)).append("\n");
    sb.append("    requesterShippingEmail: ").append(toIndentedString(requesterShippingEmail)).append("\n");
    sb.append("    requesterShippingPhone: ").append(toIndentedString(requesterShippingPhone)).append("\n");
    sb.append("    requesterShippingStreet: ").append(toIndentedString(requesterShippingStreet)).append("\n");
    sb.append("    requesterShippingCity: ").append(toIndentedString(requesterShippingCity)).append("\n");
    sb.append("    requesterShippingStateProvince: ").append(toIndentedString(requesterShippingStateProvince)).append("\n");
    sb.append("    requesterShippingCountry: ").append(toIndentedString(requesterShippingCountry)).append("\n");
    sb.append("    requesterShippingPostalCode: ").append(toIndentedString(requesterShippingPostalCode)).append("\n");
    sb.append("    shippingInboundId: ").append(toIndentedString(shippingInboundId)).append("\n");
    sb.append("    shippingOutboundId: ").append(toIndentedString(shippingOutboundId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
