/*
 * RMA_RestAPI_Design_1
 * Customer Requirements from Excel Document RMA_RestAPI_Design 1.xlsx
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TacCaseStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * An RMA Case
 */
@Schema(description = "An RMA Case")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-29T19:29:38.424806759Z[GMT]")

public class RmaCase {
  @SerializedName("id")
  private String id = null;

  @SerializedName("href")
  private String href = null;

  @SerializedName("caseNumber")
  private String caseNumber = null;

  @SerializedName("caseId")
  private String caseId = null;

  @SerializedName("relatedTacCaseId")
  private String relatedTacCaseId = null;

  @SerializedName("requestType")
  private String requestType = null;

  @SerializedName("newPartSerialNumber")
  private String newPartSerialNumber = null;

  @SerializedName("FaultySerialNumber")
  private String faultySerialNumber = null;

  @SerializedName("FaultyPartNumber")
  private String faultyPartNumber = null;

  @SerializedName("ReturnedSerialNumber")
  private String returnedSerialNumber = null;

  @SerializedName("ReturnedPartNumber")
  private String returnedPartNumber = null;

  @SerializedName("CaseStatus")
  private TacCaseStatus caseStatus = null;

  @SerializedName("NewPartShippedDate")
  private OffsetDateTime newPartShippedDate = null;

  @SerializedName("NewPartDeliveredDate")
  private OffsetDateTime newPartDeliveredDate = null;

  @SerializedName("FaultyPartShippedDate")
  private OffsetDateTime faultyPartShippedDate = null;

  @SerializedName("FaultyPartDeliveredDate")
  private OffsetDateTime faultyPartDeliveredDate = null;

  @SerializedName("FailureAnalysisStartDate")
  private OffsetDateTime failureAnalysisStartDate = null;

  @SerializedName("FailureAnalysisInProgressDate")
  private OffsetDateTime failureAnalysisInProgressDate = null;

  @SerializedName("FailureAnalysisFinishedDate")
  private OffsetDateTime failureAnalysisFinishedDate = null;

  @SerializedName("ShipToStreet1")
  private String shipToStreet1 = null;

  @SerializedName("ShipToProvince")
  private String shipToProvince = null;

  @SerializedName("ShipToPostalCode")
  private String shipToPostalCode = null;

  @SerializedName("ShipToPhone")
  private String shipToPhone = null;

  @SerializedName("ShipToCountry")
  private String shipToCountry = null;

  @SerializedName("ShipToCity")
  private String shipToCity = null;

  @SerializedName("ShipToContactEmail")
  private String shipToContactEmail = null;

  @SerializedName("ShipToAttention")
  private String shipToAttention = null;

  @SerializedName("ShippedDate")
  private String shippedDate = null;

  @SerializedName("ShippedCarrier")
  private String shippedCarrier = null;

  @SerializedName("ProblemDescription")
  private String problemDescription = null;

  @SerializedName("InstallationCountry")
  private String installationCountry = null;

  @SerializedName("CustomerTrackingNumber")
  private String customerTrackingNumber = null;

  @SerializedName("ContactEmail")
  private String contactEmail = null;

  @SerializedName("VendorRmaNumber")
  private String vendorRmaNumber = null;

  public RmaCase id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RmaCase href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @Schema(description = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public RmaCase caseNumber(String caseNumber) {
    this.caseNumber = caseNumber;
    return this;
  }

   /**
   * Get caseNumber
   * @return caseNumber
  **/
  @Schema(description = "")
  public String getCaseNumber() {
    return caseNumber;
  }

  public void setCaseNumber(String caseNumber) {
    this.caseNumber = caseNumber;
  }

  public RmaCase caseId(String caseId) {
    this.caseId = caseId;
    return this;
  }

   /**
   * Get caseId
   * @return caseId
  **/
  @Schema(description = "")
  public String getCaseId() {
    return caseId;
  }

  public void setCaseId(String caseId) {
    this.caseId = caseId;
  }

  public RmaCase relatedTacCaseId(String relatedTacCaseId) {
    this.relatedTacCaseId = relatedTacCaseId;
    return this;
  }

   /**
   * Get relatedTacCaseId
   * @return relatedTacCaseId
  **/
  @Schema(description = "")
  public String getRelatedTacCaseId() {
    return relatedTacCaseId;
  }

  public void setRelatedTacCaseId(String relatedTacCaseId) {
    this.relatedTacCaseId = relatedTacCaseId;
  }

  public RmaCase requestType(String requestType) {
    this.requestType = requestType;
    return this;
  }

   /**
   * Get requestType
   * @return requestType
  **/
  @Schema(description = "")
  public String getRequestType() {
    return requestType;
  }

  public void setRequestType(String requestType) {
    this.requestType = requestType;
  }

  public RmaCase newPartSerialNumber(String newPartSerialNumber) {
    this.newPartSerialNumber = newPartSerialNumber;
    return this;
  }

   /**
   * Get newPartSerialNumber
   * @return newPartSerialNumber
  **/
  @Schema(description = "")
  public String getNewPartSerialNumber() {
    return newPartSerialNumber;
  }

  public void setNewPartSerialNumber(String newPartSerialNumber) {
    this.newPartSerialNumber = newPartSerialNumber;
  }

  public RmaCase faultySerialNumber(String faultySerialNumber) {
    this.faultySerialNumber = faultySerialNumber;
    return this;
  }

   /**
   * Get faultySerialNumber
   * @return faultySerialNumber
  **/
  @Schema(description = "")
  public String getFaultySerialNumber() {
    return faultySerialNumber;
  }

  public void setFaultySerialNumber(String faultySerialNumber) {
    this.faultySerialNumber = faultySerialNumber;
  }

  public RmaCase faultyPartNumber(String faultyPartNumber) {
    this.faultyPartNumber = faultyPartNumber;
    return this;
  }

   /**
   * Get faultyPartNumber
   * @return faultyPartNumber
  **/
  @Schema(description = "")
  public String getFaultyPartNumber() {
    return faultyPartNumber;
  }

  public void setFaultyPartNumber(String faultyPartNumber) {
    this.faultyPartNumber = faultyPartNumber;
  }

  public RmaCase returnedSerialNumber(String returnedSerialNumber) {
    this.returnedSerialNumber = returnedSerialNumber;
    return this;
  }

   /**
   * Get returnedSerialNumber
   * @return returnedSerialNumber
  **/
  @Schema(description = "")
  public String getReturnedSerialNumber() {
    return returnedSerialNumber;
  }

  public void setReturnedSerialNumber(String returnedSerialNumber) {
    this.returnedSerialNumber = returnedSerialNumber;
  }

  public RmaCase returnedPartNumber(String returnedPartNumber) {
    this.returnedPartNumber = returnedPartNumber;
    return this;
  }

   /**
   * Get returnedPartNumber
   * @return returnedPartNumber
  **/
  @Schema(description = "")
  public String getReturnedPartNumber() {
    return returnedPartNumber;
  }

  public void setReturnedPartNumber(String returnedPartNumber) {
    this.returnedPartNumber = returnedPartNumber;
  }

  public RmaCase caseStatus(TacCaseStatus caseStatus) {
    this.caseStatus = caseStatus;
    return this;
  }

   /**
   * Get caseStatus
   * @return caseStatus
  **/
  @Schema(description = "")
  public TacCaseStatus getCaseStatus() {
    return caseStatus;
  }

  public void setCaseStatus(TacCaseStatus caseStatus) {
    this.caseStatus = caseStatus;
  }

  public RmaCase newPartShippedDate(OffsetDateTime newPartShippedDate) {
    this.newPartShippedDate = newPartShippedDate;
    return this;
  }

   /**
   * Get newPartShippedDate
   * @return newPartShippedDate
  **/
  @Schema(description = "")
  public OffsetDateTime getNewPartShippedDate() {
    return newPartShippedDate;
  }

  public void setNewPartShippedDate(OffsetDateTime newPartShippedDate) {
    this.newPartShippedDate = newPartShippedDate;
  }

  public RmaCase newPartDeliveredDate(OffsetDateTime newPartDeliveredDate) {
    this.newPartDeliveredDate = newPartDeliveredDate;
    return this;
  }

   /**
   * Get newPartDeliveredDate
   * @return newPartDeliveredDate
  **/
  @Schema(description = "")
  public OffsetDateTime getNewPartDeliveredDate() {
    return newPartDeliveredDate;
  }

  public void setNewPartDeliveredDate(OffsetDateTime newPartDeliveredDate) {
    this.newPartDeliveredDate = newPartDeliveredDate;
  }

  public RmaCase faultyPartShippedDate(OffsetDateTime faultyPartShippedDate) {
    this.faultyPartShippedDate = faultyPartShippedDate;
    return this;
  }

   /**
   * Get faultyPartShippedDate
   * @return faultyPartShippedDate
  **/
  @Schema(description = "")
  public OffsetDateTime getFaultyPartShippedDate() {
    return faultyPartShippedDate;
  }

  public void setFaultyPartShippedDate(OffsetDateTime faultyPartShippedDate) {
    this.faultyPartShippedDate = faultyPartShippedDate;
  }

  public RmaCase faultyPartDeliveredDate(OffsetDateTime faultyPartDeliveredDate) {
    this.faultyPartDeliveredDate = faultyPartDeliveredDate;
    return this;
  }

   /**
   * Get faultyPartDeliveredDate
   * @return faultyPartDeliveredDate
  **/
  @Schema(description = "")
  public OffsetDateTime getFaultyPartDeliveredDate() {
    return faultyPartDeliveredDate;
  }

  public void setFaultyPartDeliveredDate(OffsetDateTime faultyPartDeliveredDate) {
    this.faultyPartDeliveredDate = faultyPartDeliveredDate;
  }

  public RmaCase failureAnalysisStartDate(OffsetDateTime failureAnalysisStartDate) {
    this.failureAnalysisStartDate = failureAnalysisStartDate;
    return this;
  }

   /**
   * Get failureAnalysisStartDate
   * @return failureAnalysisStartDate
  **/
  @Schema(description = "")
  public OffsetDateTime getFailureAnalysisStartDate() {
    return failureAnalysisStartDate;
  }

  public void setFailureAnalysisStartDate(OffsetDateTime failureAnalysisStartDate) {
    this.failureAnalysisStartDate = failureAnalysisStartDate;
  }

  public RmaCase failureAnalysisInProgressDate(OffsetDateTime failureAnalysisInProgressDate) {
    this.failureAnalysisInProgressDate = failureAnalysisInProgressDate;
    return this;
  }

   /**
   * Get failureAnalysisInProgressDate
   * @return failureAnalysisInProgressDate
  **/
  @Schema(description = "")
  public OffsetDateTime getFailureAnalysisInProgressDate() {
    return failureAnalysisInProgressDate;
  }

  public void setFailureAnalysisInProgressDate(OffsetDateTime failureAnalysisInProgressDate) {
    this.failureAnalysisInProgressDate = failureAnalysisInProgressDate;
  }

  public RmaCase failureAnalysisFinishedDate(OffsetDateTime failureAnalysisFinishedDate) {
    this.failureAnalysisFinishedDate = failureAnalysisFinishedDate;
    return this;
  }

   /**
   * Get failureAnalysisFinishedDate
   * @return failureAnalysisFinishedDate
  **/
  @Schema(description = "")
  public OffsetDateTime getFailureAnalysisFinishedDate() {
    return failureAnalysisFinishedDate;
  }

  public void setFailureAnalysisFinishedDate(OffsetDateTime failureAnalysisFinishedDate) {
    this.failureAnalysisFinishedDate = failureAnalysisFinishedDate;
  }

  public RmaCase shipToStreet1(String shipToStreet1) {
    this.shipToStreet1 = shipToStreet1;
    return this;
  }

   /**
   * Get shipToStreet1
   * @return shipToStreet1
  **/
  @Schema(description = "")
  public String getShipToStreet1() {
    return shipToStreet1;
  }

  public void setShipToStreet1(String shipToStreet1) {
    this.shipToStreet1 = shipToStreet1;
  }

  public RmaCase shipToProvince(String shipToProvince) {
    this.shipToProvince = shipToProvince;
    return this;
  }

   /**
   * Get shipToProvince
   * @return shipToProvince
  **/
  @Schema(description = "")
  public String getShipToProvince() {
    return shipToProvince;
  }

  public void setShipToProvince(String shipToProvince) {
    this.shipToProvince = shipToProvince;
  }

  public RmaCase shipToPostalCode(String shipToPostalCode) {
    this.shipToPostalCode = shipToPostalCode;
    return this;
  }

   /**
   * Get shipToPostalCode
   * @return shipToPostalCode
  **/
  @Schema(description = "")
  public String getShipToPostalCode() {
    return shipToPostalCode;
  }

  public void setShipToPostalCode(String shipToPostalCode) {
    this.shipToPostalCode = shipToPostalCode;
  }

  public RmaCase shipToPhone(String shipToPhone) {
    this.shipToPhone = shipToPhone;
    return this;
  }

   /**
   * Get shipToPhone
   * @return shipToPhone
  **/
  @Schema(description = "")
  public String getShipToPhone() {
    return shipToPhone;
  }

  public void setShipToPhone(String shipToPhone) {
    this.shipToPhone = shipToPhone;
  }

  public RmaCase shipToCountry(String shipToCountry) {
    this.shipToCountry = shipToCountry;
    return this;
  }

   /**
   * Get shipToCountry
   * @return shipToCountry
  **/
  @Schema(description = "")
  public String getShipToCountry() {
    return shipToCountry;
  }

  public void setShipToCountry(String shipToCountry) {
    this.shipToCountry = shipToCountry;
  }

  public RmaCase shipToCity(String shipToCity) {
    this.shipToCity = shipToCity;
    return this;
  }

   /**
   * Get shipToCity
   * @return shipToCity
  **/
  @Schema(description = "")
  public String getShipToCity() {
    return shipToCity;
  }

  public void setShipToCity(String shipToCity) {
    this.shipToCity = shipToCity;
  }

  public RmaCase shipToContactEmail(String shipToContactEmail) {
    this.shipToContactEmail = shipToContactEmail;
    return this;
  }

   /**
   * Get shipToContactEmail
   * @return shipToContactEmail
  **/
  @Schema(description = "")
  public String getShipToContactEmail() {
    return shipToContactEmail;
  }

  public void setShipToContactEmail(String shipToContactEmail) {
    this.shipToContactEmail = shipToContactEmail;
  }

  public RmaCase shipToAttention(String shipToAttention) {
    this.shipToAttention = shipToAttention;
    return this;
  }

   /**
   * Get shipToAttention
   * @return shipToAttention
  **/
  @Schema(description = "")
  public String getShipToAttention() {
    return shipToAttention;
  }

  public void setShipToAttention(String shipToAttention) {
    this.shipToAttention = shipToAttention;
  }

  public RmaCase shippedDate(String shippedDate) {
    this.shippedDate = shippedDate;
    return this;
  }

   /**
   * Get shippedDate
   * @return shippedDate
  **/
  @Schema(description = "")
  public String getShippedDate() {
    return shippedDate;
  }

  public void setShippedDate(String shippedDate) {
    this.shippedDate = shippedDate;
  }

  public RmaCase shippedCarrier(String shippedCarrier) {
    this.shippedCarrier = shippedCarrier;
    return this;
  }

   /**
   * Get shippedCarrier
   * @return shippedCarrier
  **/
  @Schema(description = "")
  public String getShippedCarrier() {
    return shippedCarrier;
  }

  public void setShippedCarrier(String shippedCarrier) {
    this.shippedCarrier = shippedCarrier;
  }

  public RmaCase problemDescription(String problemDescription) {
    this.problemDescription = problemDescription;
    return this;
  }

   /**
   * Get problemDescription
   * @return problemDescription
  **/
  @Schema(description = "")
  public String getProblemDescription() {
    return problemDescription;
  }

  public void setProblemDescription(String problemDescription) {
    this.problemDescription = problemDescription;
  }

  public RmaCase installationCountry(String installationCountry) {
    this.installationCountry = installationCountry;
    return this;
  }

   /**
   * Get installationCountry
   * @return installationCountry
  **/
  @Schema(description = "")
  public String getInstallationCountry() {
    return installationCountry;
  }

  public void setInstallationCountry(String installationCountry) {
    this.installationCountry = installationCountry;
  }

  public RmaCase customerTrackingNumber(String customerTrackingNumber) {
    this.customerTrackingNumber = customerTrackingNumber;
    return this;
  }

   /**
   * Get customerTrackingNumber
   * @return customerTrackingNumber
  **/
  @Schema(description = "")
  public String getCustomerTrackingNumber() {
    return customerTrackingNumber;
  }

  public void setCustomerTrackingNumber(String customerTrackingNumber) {
    this.customerTrackingNumber = customerTrackingNumber;
  }

  public RmaCase contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * Get contactEmail
   * @return contactEmail
  **/
  @Schema(description = "")
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public RmaCase vendorRmaNumber(String vendorRmaNumber) {
    this.vendorRmaNumber = vendorRmaNumber;
    return this;
  }

   /**
   * Get vendorRmaNumber
   * @return vendorRmaNumber
  **/
  @Schema(description = "")
  public String getVendorRmaNumber() {
    return vendorRmaNumber;
  }

  public void setVendorRmaNumber(String vendorRmaNumber) {
    this.vendorRmaNumber = vendorRmaNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RmaCase rmaCase = (RmaCase) o;
    return Objects.equals(this.id, rmaCase.id) &&
        Objects.equals(this.href, rmaCase.href) &&
        Objects.equals(this.caseNumber, rmaCase.caseNumber) &&
        Objects.equals(this.caseId, rmaCase.caseId) &&
        Objects.equals(this.relatedTacCaseId, rmaCase.relatedTacCaseId) &&
        Objects.equals(this.requestType, rmaCase.requestType) &&
        Objects.equals(this.newPartSerialNumber, rmaCase.newPartSerialNumber) &&
        Objects.equals(this.faultySerialNumber, rmaCase.faultySerialNumber) &&
        Objects.equals(this.faultyPartNumber, rmaCase.faultyPartNumber) &&
        Objects.equals(this.returnedSerialNumber, rmaCase.returnedSerialNumber) &&
        Objects.equals(this.returnedPartNumber, rmaCase.returnedPartNumber) &&
        Objects.equals(this.caseStatus, rmaCase.caseStatus) &&
        Objects.equals(this.newPartShippedDate, rmaCase.newPartShippedDate) &&
        Objects.equals(this.newPartDeliveredDate, rmaCase.newPartDeliveredDate) &&
        Objects.equals(this.faultyPartShippedDate, rmaCase.faultyPartShippedDate) &&
        Objects.equals(this.faultyPartDeliveredDate, rmaCase.faultyPartDeliveredDate) &&
        Objects.equals(this.failureAnalysisStartDate, rmaCase.failureAnalysisStartDate) &&
        Objects.equals(this.failureAnalysisInProgressDate, rmaCase.failureAnalysisInProgressDate) &&
        Objects.equals(this.failureAnalysisFinishedDate, rmaCase.failureAnalysisFinishedDate) &&
        Objects.equals(this.shipToStreet1, rmaCase.shipToStreet1) &&
        Objects.equals(this.shipToProvince, rmaCase.shipToProvince) &&
        Objects.equals(this.shipToPostalCode, rmaCase.shipToPostalCode) &&
        Objects.equals(this.shipToPhone, rmaCase.shipToPhone) &&
        Objects.equals(this.shipToCountry, rmaCase.shipToCountry) &&
        Objects.equals(this.shipToCity, rmaCase.shipToCity) &&
        Objects.equals(this.shipToContactEmail, rmaCase.shipToContactEmail) &&
        Objects.equals(this.shipToAttention, rmaCase.shipToAttention) &&
        Objects.equals(this.shippedDate, rmaCase.shippedDate) &&
        Objects.equals(this.shippedCarrier, rmaCase.shippedCarrier) &&
        Objects.equals(this.problemDescription, rmaCase.problemDescription) &&
        Objects.equals(this.installationCountry, rmaCase.installationCountry) &&
        Objects.equals(this.customerTrackingNumber, rmaCase.customerTrackingNumber) &&
        Objects.equals(this.contactEmail, rmaCase.contactEmail) &&
        Objects.equals(this.vendorRmaNumber, rmaCase.vendorRmaNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href, caseNumber, caseId, relatedTacCaseId, requestType, newPartSerialNumber, faultySerialNumber, faultyPartNumber, returnedSerialNumber, returnedPartNumber, caseStatus, newPartShippedDate, newPartDeliveredDate, faultyPartShippedDate, faultyPartDeliveredDate, failureAnalysisStartDate, failureAnalysisInProgressDate, failureAnalysisFinishedDate, shipToStreet1, shipToProvince, shipToPostalCode, shipToPhone, shipToCountry, shipToCity, shipToContactEmail, shipToAttention, shippedDate, shippedCarrier, problemDescription, installationCountry, customerTrackingNumber, contactEmail, vendorRmaNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RmaCase {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    caseNumber: ").append(toIndentedString(caseNumber)).append("\n");
    sb.append("    caseId: ").append(toIndentedString(caseId)).append("\n");
    sb.append("    relatedTacCaseId: ").append(toIndentedString(relatedTacCaseId)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    newPartSerialNumber: ").append(toIndentedString(newPartSerialNumber)).append("\n");
    sb.append("    faultySerialNumber: ").append(toIndentedString(faultySerialNumber)).append("\n");
    sb.append("    faultyPartNumber: ").append(toIndentedString(faultyPartNumber)).append("\n");
    sb.append("    returnedSerialNumber: ").append(toIndentedString(returnedSerialNumber)).append("\n");
    sb.append("    returnedPartNumber: ").append(toIndentedString(returnedPartNumber)).append("\n");
    sb.append("    caseStatus: ").append(toIndentedString(caseStatus)).append("\n");
    sb.append("    newPartShippedDate: ").append(toIndentedString(newPartShippedDate)).append("\n");
    sb.append("    newPartDeliveredDate: ").append(toIndentedString(newPartDeliveredDate)).append("\n");
    sb.append("    faultyPartShippedDate: ").append(toIndentedString(faultyPartShippedDate)).append("\n");
    sb.append("    faultyPartDeliveredDate: ").append(toIndentedString(faultyPartDeliveredDate)).append("\n");
    sb.append("    failureAnalysisStartDate: ").append(toIndentedString(failureAnalysisStartDate)).append("\n");
    sb.append("    failureAnalysisInProgressDate: ").append(toIndentedString(failureAnalysisInProgressDate)).append("\n");
    sb.append("    failureAnalysisFinishedDate: ").append(toIndentedString(failureAnalysisFinishedDate)).append("\n");
    sb.append("    shipToStreet1: ").append(toIndentedString(shipToStreet1)).append("\n");
    sb.append("    shipToProvince: ").append(toIndentedString(shipToProvince)).append("\n");
    sb.append("    shipToPostalCode: ").append(toIndentedString(shipToPostalCode)).append("\n");
    sb.append("    shipToPhone: ").append(toIndentedString(shipToPhone)).append("\n");
    sb.append("    shipToCountry: ").append(toIndentedString(shipToCountry)).append("\n");
    sb.append("    shipToCity: ").append(toIndentedString(shipToCity)).append("\n");
    sb.append("    shipToContactEmail: ").append(toIndentedString(shipToContactEmail)).append("\n");
    sb.append("    shipToAttention: ").append(toIndentedString(shipToAttention)).append("\n");
    sb.append("    shippedDate: ").append(toIndentedString(shippedDate)).append("\n");
    sb.append("    shippedCarrier: ").append(toIndentedString(shippedCarrier)).append("\n");
    sb.append("    problemDescription: ").append(toIndentedString(problemDescription)).append("\n");
    sb.append("    installationCountry: ").append(toIndentedString(installationCountry)).append("\n");
    sb.append("    customerTrackingNumber: ").append(toIndentedString(customerTrackingNumber)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    vendorRmaNumber: ").append(toIndentedString(vendorRmaNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
