/*
 * RMA_RestAPI_Design_1
 * Customer Requirements from Excel Document RMA_RestAPI_Design 1.xlsx
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Note;
import io.swagger.client.model.TacCaseStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * A TAC Case
 */
@Schema(description = "A TAC Case")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-29T19:29:38.424806759Z[GMT]")

public class TacCase {
  @SerializedName("id")
  private String id = null;

  @SerializedName("href")
  private String href = null;

  @SerializedName("caseNumber")
  private String caseNumber = null;

  @SerializedName("caseStatus")
  private TacCaseStatus caseStatus = null;

  @SerializedName("rmaNeeded")
  private Boolean rmaNeeded = null;

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("relatedRmaCount")
  private Integer relatedRmaCount = null;

  @SerializedName("relatedDispatchCount")
  private Integer relatedDispatchCount = null;

  @SerializedName("problemDescription")
  private String problemDescription = null;

  @SerializedName("installationCountry")
  private String installationCountry = null;

  @SerializedName("firstResponseDate")
  private OffsetDateTime firstResponseDate = null;

  @SerializedName("customerTrackingNumber")
  private String customerTrackingNumber = null;

  @SerializedName("contactEmail")
  private String contactEmail = null;

  @SerializedName("productName")
  private String productName = null;

  @SerializedName("productSerialNumber")
  private String productSerialNumber = null;

  @SerializedName("productFirmwareVersion")
  private String productFirmwareVersion = null;

  @SerializedName("productSoftwareVersion")
  private String productSoftwareVersion = null;

  @SerializedName("caseSolutionDescription")
  private String caseSolutionDescription = null;

  /**
   * The priorty assigned by TAC to this Case
   */
  @JsonAdapter(CasePriorityEnum.Adapter.class)
  public enum CasePriorityEnum {
    @SerializedName("Critical")
    CRITICAL("Critical"),
    @SerializedName("Major")
    MAJOR("Major"),
    @SerializedName("Minor")
    MINOR("Minor");

    private String value;

    CasePriorityEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static CasePriorityEnum fromValue(String input) {
      for (CasePriorityEnum b : CasePriorityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<CasePriorityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CasePriorityEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public CasePriorityEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return CasePriorityEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("casePriority")
  private CasePriorityEnum casePriority = null;

  @SerializedName("caseOwner")
  private String caseOwner = null;

  @SerializedName("caseNoteCount")
  private Integer caseNoteCount = null;

  @SerializedName("caseCreatedDate")
  private OffsetDateTime caseCreatedDate = null;

  @SerializedName("caseClosedDate")
  private OffsetDateTime caseClosedDate = null;

  @SerializedName("businessImpact")
  private String businessImpact = null;

  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("notes")
  private List<Note> notes = null;

  public TacCase id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the TAC Case
   * @return id
  **/
  @Schema(description = "Unique identifier of the TAC Case")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TacCase href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Hyperlink, a reference to the TAC Case entity
   * @return href
  **/
  @Schema(description = "Hyperlink, a reference to the TAC Case entity")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public TacCase caseNumber(String caseNumber) {
    this.caseNumber = caseNumber;
    return this;
  }

   /**
   * Same as ID, requested by customer
   * @return caseNumber
  **/
  @Schema(description = "Same as ID, requested by customer")
  public String getCaseNumber() {
    return caseNumber;
  }

  public void setCaseNumber(String caseNumber) {
    this.caseNumber = caseNumber;
  }

  public TacCase caseStatus(TacCaseStatus caseStatus) {
    this.caseStatus = caseStatus;
    return this;
  }

   /**
   * Get caseStatus
   * @return caseStatus
  **/
  @Schema(description = "")
  public TacCaseStatus getCaseStatus() {
    return caseStatus;
  }

  public void setCaseStatus(TacCaseStatus caseStatus) {
    this.caseStatus = caseStatus;
  }

  public TacCase rmaNeeded(Boolean rmaNeeded) {
    this.rmaNeeded = rmaNeeded;
    return this;
  }

   /**
   * TAC indicates RMA is required
   * @return rmaNeeded
  **/
  @Schema(description = "TAC indicates RMA is required")
  public Boolean isRmaNeeded() {
    return rmaNeeded;
  }

  public void setRmaNeeded(Boolean rmaNeeded) {
    this.rmaNeeded = rmaNeeded;
  }

  public TacCase subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Subject of TAC Case
   * @return subject
  **/
  @Schema(description = "Subject of TAC Case")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public TacCase relatedRmaCount(Integer relatedRmaCount) {
    this.relatedRmaCount = relatedRmaCount;
    return this;
  }

   /**
   * Number of RMAs related to this TAC Case
   * @return relatedRmaCount
  **/
  @Schema(description = "Number of RMAs related to this TAC Case")
  public Integer getRelatedRmaCount() {
    return relatedRmaCount;
  }

  public void setRelatedRmaCount(Integer relatedRmaCount) {
    this.relatedRmaCount = relatedRmaCount;
  }

  public TacCase relatedDispatchCount(Integer relatedDispatchCount) {
    this.relatedDispatchCount = relatedDispatchCount;
    return this;
  }

   /**
   * Number of dispatches related to this TAC Case
   * @return relatedDispatchCount
  **/
  @Schema(description = "Number of dispatches related to this TAC Case")
  public Integer getRelatedDispatchCount() {
    return relatedDispatchCount;
  }

  public void setRelatedDispatchCount(Integer relatedDispatchCount) {
    this.relatedDispatchCount = relatedDispatchCount;
  }

  public TacCase problemDescription(String problemDescription) {
    this.problemDescription = problemDescription;
    return this;
  }

   /**
   * A description of the problem assocated with this TAC Case
   * @return problemDescription
  **/
  @Schema(description = "A description of the problem assocated with this TAC Case")
  public String getProblemDescription() {
    return problemDescription;
  }

  public void setProblemDescription(String problemDescription) {
    this.problemDescription = problemDescription;
  }

  public TacCase installationCountry(String installationCountry) {
    this.installationCountry = installationCountry;
    return this;
  }

   /**
   * Get installationCountry
   * @return installationCountry
  **/
  @Schema(example = "[\"US\",\"CA\",\"CN\",\"MX\",\"UK\"]", description = "")
  public String getInstallationCountry() {
    return installationCountry;
  }

  public void setInstallationCountry(String installationCountry) {
    this.installationCountry = installationCountry;
  }

  public TacCase firstResponseDate(OffsetDateTime firstResponseDate) {
    this.firstResponseDate = firstResponseDate;
    return this;
  }

   /**
   * The date of first response from the TAC to this Case
   * @return firstResponseDate
  **/
  @Schema(description = "The date of first response from the TAC to this Case")
  public OffsetDateTime getFirstResponseDate() {
    return firstResponseDate;
  }

  public void setFirstResponseDate(OffsetDateTime firstResponseDate) {
    this.firstResponseDate = firstResponseDate;
  }

  public TacCase customerTrackingNumber(String customerTrackingNumber) {
    this.customerTrackingNumber = customerTrackingNumber;
    return this;
  }

   /**
   * A Reference to the customer&#x27;s issue associated with this Case
   * @return customerTrackingNumber
  **/
  @Schema(description = "A Reference to the customer's issue associated with this Case")
  public String getCustomerTrackingNumber() {
    return customerTrackingNumber;
  }

  public void setCustomerTrackingNumber(String customerTrackingNumber) {
    this.customerTrackingNumber = customerTrackingNumber;
  }

  public TacCase contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * The email of the customer contact related to this Case
   * @return contactEmail
  **/
  @Schema(description = "The email of the customer contact related to this Case")
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public TacCase productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * The name of the product associated with this TAC Case
   * @return productName
  **/
  @Schema(description = "The name of the product associated with this TAC Case")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public TacCase productSerialNumber(String productSerialNumber) {
    this.productSerialNumber = productSerialNumber;
    return this;
  }

   /**
   * The serial number of the product associcated with this TAC Case
   * @return productSerialNumber
  **/
  @Schema(description = "The serial number of the product associcated with this TAC Case")
  public String getProductSerialNumber() {
    return productSerialNumber;
  }

  public void setProductSerialNumber(String productSerialNumber) {
    this.productSerialNumber = productSerialNumber;
  }

  public TacCase productFirmwareVersion(String productFirmwareVersion) {
    this.productFirmwareVersion = productFirmwareVersion;
    return this;
  }

   /**
   * The version number of the product associcated with this TAC Case
   * @return productFirmwareVersion
  **/
  @Schema(description = "The version number of the product associcated with this TAC Case")
  public String getProductFirmwareVersion() {
    return productFirmwareVersion;
  }

  public void setProductFirmwareVersion(String productFirmwareVersion) {
    this.productFirmwareVersion = productFirmwareVersion;
  }

  public TacCase productSoftwareVersion(String productSoftwareVersion) {
    this.productSoftwareVersion = productSoftwareVersion;
    return this;
  }

   /**
   * The version number of the product associcated with this TAC Case
   * @return productSoftwareVersion
  **/
  @Schema(description = "The version number of the product associcated with this TAC Case")
  public String getProductSoftwareVersion() {
    return productSoftwareVersion;
  }

  public void setProductSoftwareVersion(String productSoftwareVersion) {
    this.productSoftwareVersion = productSoftwareVersion;
  }

  public TacCase caseSolutionDescription(String caseSolutionDescription) {
    this.caseSolutionDescription = caseSolutionDescription;
    return this;
  }

   /**
   * A general summary of the solution to this Case
   * @return caseSolutionDescription
  **/
  @Schema(description = "A general summary of the solution to this Case")
  public String getCaseSolutionDescription() {
    return caseSolutionDescription;
  }

  public void setCaseSolutionDescription(String caseSolutionDescription) {
    this.caseSolutionDescription = caseSolutionDescription;
  }

  public TacCase casePriority(CasePriorityEnum casePriority) {
    this.casePriority = casePriority;
    return this;
  }

   /**
   * The priorty assigned by TAC to this Case
   * @return casePriority
  **/
  @Schema(description = "The priorty assigned by TAC to this Case")
  public CasePriorityEnum getCasePriority() {
    return casePriority;
  }

  public void setCasePriority(CasePriorityEnum casePriority) {
    this.casePriority = casePriority;
  }

  public TacCase caseOwner(String caseOwner) {
    this.caseOwner = caseOwner;
    return this;
  }

   /**
   * The TAC name associated with the ownership of this Case
   * @return caseOwner
  **/
  @Schema(description = "The TAC name associated with the ownership of this Case")
  public String getCaseOwner() {
    return caseOwner;
  }

  public void setCaseOwner(String caseOwner) {
    this.caseOwner = caseOwner;
  }

  public TacCase caseNoteCount(Integer caseNoteCount) {
    this.caseNoteCount = caseNoteCount;
    return this;
  }

   /**
   * The number of notes associated with this Case
   * @return caseNoteCount
  **/
  @Schema(description = "The number of notes associated with this Case")
  public Integer getCaseNoteCount() {
    return caseNoteCount;
  }

  public void setCaseNoteCount(Integer caseNoteCount) {
    this.caseNoteCount = caseNoteCount;
  }

  public TacCase caseCreatedDate(OffsetDateTime caseCreatedDate) {
    this.caseCreatedDate = caseCreatedDate;
    return this;
  }

   /**
   * The date this Case was created by Customer
   * @return caseCreatedDate
  **/
  @Schema(description = "The date this Case was created by Customer")
  public OffsetDateTime getCaseCreatedDate() {
    return caseCreatedDate;
  }

  public void setCaseCreatedDate(OffsetDateTime caseCreatedDate) {
    this.caseCreatedDate = caseCreatedDate;
  }

  public TacCase caseClosedDate(OffsetDateTime caseClosedDate) {
    this.caseClosedDate = caseClosedDate;
    return this;
  }

   /**
   * The date this Case was closed by Customer or TAC
   * @return caseClosedDate
  **/
  @Schema(description = "The date this Case was closed by Customer or TAC")
  public OffsetDateTime getCaseClosedDate() {
    return caseClosedDate;
  }

  public void setCaseClosedDate(OffsetDateTime caseClosedDate) {
    this.caseClosedDate = caseClosedDate;
  }

  public TacCase businessImpact(String businessImpact) {
    this.businessImpact = businessImpact;
    return this;
  }

   /**
   * The impact to the customer&#x27;s business associated with this Case
   * @return businessImpact
  **/
  @Schema(example = "[\"Critical level business impacting issue\",\"Major level business impacting issue\",\"Minor level business impacting issue\",\"Warning level business impacting issue\"]", description = "The impact to the customer's business associated with this Case")
  public String getBusinessImpact() {
    return businessImpact;
  }

  public void setBusinessImpact(String businessImpact) {
    this.businessImpact = businessImpact;
  }

  public TacCase accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * The customer&#x27;s account number associated with this ticket
   * @return accountNumber
  **/
  @Schema(description = "The customer's account number associated with this ticket")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public TacCase notes(List<Note> notes) {
    this.notes = notes;
    return this;
  }

  public TacCase addNotesItem(Note notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<Note>();
    }
    this.notes.add(notesItem);
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @Schema(description = "")
  public List<Note> getNotes() {
    return notes;
  }

  public void setNotes(List<Note> notes) {
    this.notes = notes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TacCase tacCase = (TacCase) o;
    return Objects.equals(this.id, tacCase.id) &&
        Objects.equals(this.href, tacCase.href) &&
        Objects.equals(this.caseNumber, tacCase.caseNumber) &&
        Objects.equals(this.caseStatus, tacCase.caseStatus) &&
        Objects.equals(this.rmaNeeded, tacCase.rmaNeeded) &&
        Objects.equals(this.subject, tacCase.subject) &&
        Objects.equals(this.relatedRmaCount, tacCase.relatedRmaCount) &&
        Objects.equals(this.relatedDispatchCount, tacCase.relatedDispatchCount) &&
        Objects.equals(this.problemDescription, tacCase.problemDescription) &&
        Objects.equals(this.installationCountry, tacCase.installationCountry) &&
        Objects.equals(this.firstResponseDate, tacCase.firstResponseDate) &&
        Objects.equals(this.customerTrackingNumber, tacCase.customerTrackingNumber) &&
        Objects.equals(this.contactEmail, tacCase.contactEmail) &&
        Objects.equals(this.productName, tacCase.productName) &&
        Objects.equals(this.productSerialNumber, tacCase.productSerialNumber) &&
        Objects.equals(this.productFirmwareVersion, tacCase.productFirmwareVersion) &&
        Objects.equals(this.productSoftwareVersion, tacCase.productSoftwareVersion) &&
        Objects.equals(this.caseSolutionDescription, tacCase.caseSolutionDescription) &&
        Objects.equals(this.casePriority, tacCase.casePriority) &&
        Objects.equals(this.caseOwner, tacCase.caseOwner) &&
        Objects.equals(this.caseNoteCount, tacCase.caseNoteCount) &&
        Objects.equals(this.caseCreatedDate, tacCase.caseCreatedDate) &&
        Objects.equals(this.caseClosedDate, tacCase.caseClosedDate) &&
        Objects.equals(this.businessImpact, tacCase.businessImpact) &&
        Objects.equals(this.accountNumber, tacCase.accountNumber) &&
        Objects.equals(this.notes, tacCase.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href, caseNumber, caseStatus, rmaNeeded, subject, relatedRmaCount, relatedDispatchCount, problemDescription, installationCountry, firstResponseDate, customerTrackingNumber, contactEmail, productName, productSerialNumber, productFirmwareVersion, productSoftwareVersion, caseSolutionDescription, casePriority, caseOwner, caseNoteCount, caseCreatedDate, caseClosedDate, businessImpact, accountNumber, notes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TacCase {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    caseNumber: ").append(toIndentedString(caseNumber)).append("\n");
    sb.append("    caseStatus: ").append(toIndentedString(caseStatus)).append("\n");
    sb.append("    rmaNeeded: ").append(toIndentedString(rmaNeeded)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    relatedRmaCount: ").append(toIndentedString(relatedRmaCount)).append("\n");
    sb.append("    relatedDispatchCount: ").append(toIndentedString(relatedDispatchCount)).append("\n");
    sb.append("    problemDescription: ").append(toIndentedString(problemDescription)).append("\n");
    sb.append("    installationCountry: ").append(toIndentedString(installationCountry)).append("\n");
    sb.append("    firstResponseDate: ").append(toIndentedString(firstResponseDate)).append("\n");
    sb.append("    customerTrackingNumber: ").append(toIndentedString(customerTrackingNumber)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    productSerialNumber: ").append(toIndentedString(productSerialNumber)).append("\n");
    sb.append("    productFirmwareVersion: ").append(toIndentedString(productFirmwareVersion)).append("\n");
    sb.append("    productSoftwareVersion: ").append(toIndentedString(productSoftwareVersion)).append("\n");
    sb.append("    caseSolutionDescription: ").append(toIndentedString(caseSolutionDescription)).append("\n");
    sb.append("    casePriority: ").append(toIndentedString(casePriority)).append("\n");
    sb.append("    caseOwner: ").append(toIndentedString(caseOwner)).append("\n");
    sb.append("    caseNoteCount: ").append(toIndentedString(caseNoteCount)).append("\n");
    sb.append("    caseCreatedDate: ").append(toIndentedString(caseCreatedDate)).append("\n");
    sb.append("    caseClosedDate: ").append(toIndentedString(caseClosedDate)).append("\n");
    sb.append("    businessImpact: ").append(toIndentedString(businessImpact)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
